<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Model::unguard();

        $counter = 6;

        $LNFettingsFields = [
            // Sections
            [
                'id' => 1,
                'button' => null,
                'items' => null,
                'label' => 'Global Settings',
                'placeholder' => null,
                'des' => null,
                'name' => 'global_settings',
                'type' => 'section',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // General Settings Section Name
            [
                'id' => 2,
                'button' => null,
                'items' => null,
                'label' => 'Footer Settings',
                'placeholder' => null,
                'des' => null,
                'name' => 'footer_settings',
                'type' => 'section',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Footer Section Name
            [
                'id' => 3,
                'button' => null,
                'items' => null,
                'label' => 'Mail Settings',
                'placeholder' => null,
                'des' => null,
                'name' => 'mail_settings',
                'type' => 'section',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Mail Settings Section Name
            [
                'id' => 4,
                'button' => null,
                'items' => null,
                'label' => 'Terms & Conditions',
                'placeholder' => null,
                'des' => null,
                'name' => 'tos_settings',
                'type' => 'section',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Terms & Conditions Section Name
            [
                'id' => 5,
                'button' => null,
                'items' => null,
                'label' => 'Social Media',
                'placeholder' => null,
                'des' => null,
                'name' => 'social_links',
                'type' => 'section',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => $counter++,
                'button' => null,
                'items' => null,
                'label' => 'Header Menu',
                'placeholder' => 'Header Menu',
                'des' => 'Please select your main Header Menu',
                'name' => 'header_menu',
                'type' => 'select',
                'data' => 'menus',
                'class' => null,
                'rules' => null,
                'value' => '1',
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => $counter++,
                'button' => null,
                'items' => null,
                'label' => 'Footer Menu #1',
                'placeholder' => 'Footer Menu #1',
                'des' => 'Please select your main Header Menu',
                'name' => 'footer_menu_1',
                'type' => 'select',
                'data' => 'menus',
                'class' => null,
                'rules' => null,
                'value' => '2',
                'parent_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => $counter++,
                'button' => null,
                'items' => null,
                'label' => 'Footer Menu #2',
                'placeholder' => 'Footer Menu #2',
                'des' => 'Please select your main Header Menu',
                'name' => 'footer_menu_2',
                'type' => 'select',
                'data' => 'menus',
                'class' => null,
                'rules' => null,
                'value' => '3',
                'parent_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => $counter++,
                'button' => null,
                'items' => null,
                'label' => 'Footer Menu #3',
                'placeholder' => 'Footer Menu #3',
                'des' => 'Please select your main Header Menu',
                'name' => 'footer_menu_3',
                'type' => 'select',
                'data' => 'menus',
                'class' => null,
                'rules' => null,
                'value' => '4',
                'parent_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => $counter++,
                'button' => null,
                'items' => null,
                'label' => 'Footer Menu #4',
                'placeholder' => 'Footer Menu #4',
                'des' => 'Please select your main Header Menu',
                'name' => 'footer_menu_4',
                'type' => 'select',
                'data' => 'menus',
                'class' => null,
                'rules' => null,
                'value' => '5',
                'parent_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            // General Settings
            [
                'id' => $counter++,
                'button' => null,
                'items' => null,
                'label' => ' LNF App Title/Name',
                'placeholder' => 'For Example: " LNF"',
                'des' => ' LNF SEO Title',
                'name' => 'app_name',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => ' LNF',
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // App Name
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'LNF Logo Light',
                'placeholder' => null,
                'des' => 'LNF logo for Light mode',
                'name' => 'app_logo_light',
                'type' => 'uploader',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Logo Light Mode
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'LNF Logo Dark',
                'placeholder' => null,
                'des' => 'LNF logo for dark mode',
                'name' => 'app_logo_dark',
                'type' => 'uploader',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Logo Dark Mode
            [
                'id' => $counter++,
                'items' => null,
                'label' => 'Register Button Label',
                'placeholder' => null,
                'des' => 'Register Button Label',
                'name' => 'register_button',
                'type' => 'button',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'button' => '{"label": "Register","url": "/register","target": "_self","icon": "solar:login-2-broken","style": "primary"}',
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Register Button
            [
                'id' => $counter++,
                'items' => null,
                'label' => 'Login Button Label',
                'placeholder' => null,
                'des' => 'Login Button Label',
                'name' => 'login_button',
                'type' => 'button',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'button' => '{"label": "Login","url": "/login","target": "_self","icon": "solar:home-add-angle-broken","style": "primary"}',
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Login Button
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Show Register Button',
                'placeholder' => null,
                'des' => null,
                'name' => 'register_button_active',
                'type' => 'boolean',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 1,
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Activate Register Button
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Show Login Button',
                'placeholder' => null,
                'des' => null,
                'name' => 'login_button_active',
                'type' => 'boolean',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 1,
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Activate Login Button

            // Footer Settings Section
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Copyrights Text',
                'placeholder' => 'Copyrights Text',
                'des' => null,
                'name' => 'copyrights_text',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 'Empowered by Logistics Network Federation',
                'parent_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Copyrights Text
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Short Description',
                'placeholder' => 'Short Description',
                'des' => null,
                'name' => 'app_short_description',
                'type' => 'textarea',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 'The Logistics Network Federation (LNF) stands as a beacon of cooperative strength and shared vision, transcending the traditional boundaries of competition.',
                'parent_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // App Short Description


            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'NewsLetter Title',
                'placeholder' => 'Newsletter Title',
                'des' => 'This is Newsletter Title',
                'name' => 'newsletter_form_title',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 'Newsletter',
                'parent_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Newsletter Title
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Newsletter Description',
                'placeholder' => 'Newsletter Description',
                'des' => 'This is Newsletter Description',
                'name' => 'newsletter_form_description',
                'type' => 'textarea',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 'To stay up-to-date with our news and exclusive insights we welcome you to subscribe to our newsletter.',
                'parent_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Newsletter Description

            // Mail Settings
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Mail Protocol',
                'placeholder' => 'SMTP, IMAP...',
                'des' => null,
                'name' => 'mail_mailer',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 'smtp',
                'parent_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Mail Protocol
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Mail Host',
                'placeholder' => 'smtp.mail-provider.com',
                'des' => null,
                'name' => 'mail_host',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 'smtp.gmail.com',
                'parent_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Mail Host
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Mail Port',
                'placeholder' => '123',
                'des' => null,
                'name' => 'mail_port',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => '465',
                'parent_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Mail Port
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Mail Username',
                'placeholder' => 'name@domain-name.com',
                'des' => null,
                'name' => 'mail_username',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 'info@lnfederation.com',
                'parent_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Mail Username
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Mail Password',
                'placeholder' => '********',
                'des' => null,
                'name' => 'mail_password',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 'info@info',
                'parent_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Mail Password
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Mail Encryption',
                'placeholder' => 'tls, s/mime, pgp',
                'des' => null,
                'name' => 'mail_encryption',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 'ssl',
                'parent_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Mail Encryption
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'From Email',
                'placeholder' => 'hello@example.com',
                'des' => null,
                'name' => 'mail_from_address',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => 'info@lnfederation.com',
                'parent_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // From Email
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'From Name',
                'placeholder' => 'hello@example.com',
                'des' => null,
                'name' => 'mail_from_name',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // From Name

            // Terms & Conditions
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Waiver Title',
                'placeholder' => 'Waiver Title',
                'des' => null,
                'name' => 'tos_waiver_title',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            // Social Media Icons
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Facebook Link',
                'placeholder' => 'Facebook Link',
                'des' => null,
                'name' => 'social_facebook',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Facebook
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Linkedin Link',
                'placeholder' => 'Linkedin Link',
                'des' => null,
                'name' => 'social_linkedin',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Linkedin
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Youtube Link',
                'placeholder' => 'Youtube Link',
                'des' => null,
                'name' => 'social_youtube',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Youtube
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'Instagram Link',
                'placeholder' => 'Instagram Link',
                'des' => null,
                'name' => 'social_instagram',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ], // Instagram
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'X formerly Twitter Link',
                'placeholder' => 'X formerly Twitter Link',
                'des' => null,
                'name' => 'social_twitter',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => null,
                'parent_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => $counter++,
                'items' => null,
                'button' => null,
                'label' => 'ADDRESS',
                'placeholder' => 'ADDRESS',
                'des' => null,
                'name' => 'office_address',
                'type' => 'text',
                'data' => null,
                'class' => null,
                'rules' => null,
                'value' => '1 Meadowlands Plaza Suite 200, East Rutherford, New Jersey. 07073.',
                'parent_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ]
        ];

        DB::table('settings')->insert($LNFettingsFields);
    }
}
